### ISSUE TITLE
A lot is still missing

### ISSUE THREAD

**Issue by fyozt** [iMoD1998/DLL-Proxy-Generator#3]
Missing .h file reference; lack of judgment in this location

**Comment by iMoD1998** [comment]
Sorry didn't spot this issue.

What do you mean?

**Comment by fyozt** [comment]
> Sorry didn't spot this issue.
> 
> What do you mean?

Can you come to two examples?
![image](https://user-images.githubusercontent.com/33294277/104017746-a1e56400-51f3-11eb-9fb4-447ce9c9dedd.png)
Similar to the two methods on the picture！

**Comment by iMoD1998** [comment]
This program also can also generate projects for DLL export forwarding but I'm failing to understand the actual issue.
